# Generated by Django 6.0.5 on 2026-06-08 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kukat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlg', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Col',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col', models.CharField(max_length=50)),
                ('vlgf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='day14.kukat')),
            ],
        ),
        migrations.CreateModel(
            name='vr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('vlgfr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='day14.kukat')),
            ],
        ),
    ]
