# Generated by Django 6.0.5 on 2026-06-09 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day14', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='col',
            name='vlgf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t2', to='day14.kukat'),
        ),
        migrations.AlterField(
            model_name='vr',
            name='vlgfr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='t3', to='day14.kukat'),
        ),
    ]
