# Generated by Django 6.0.5 on 2026-05-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='murthy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('num', models.IntegerField()),
                ('adds', models.CharField(max_length=50)),
            ],
        ),
    ]
