# Generated by Django 6.0.6 on 2026-06-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doornum', models.CharField(max_length=50, unique=True)),
                ('mem', models.IntegerField()),
                ('famhead', models.CharField(max_length=50)),
                ('income', models.IntegerField()),
            ],
        ),
    ]
