# Generated by Django 6.0.5 on 2026-05-31 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=50)),
                ('hod', models.CharField(max_length=50)),
                ('salary', models.FloatField()),
                ('staff', models.FloatField()),
                ('students', models.IntegerField()),
            ],
        ),
    ]
