# Generated by Django 6.0.5 on 2026-06-04 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day12', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=50)),
                ('hod', models.CharField(max_length=50)),
                ('salary', models.FloatField()),
                ('staff', models.FloatField()),
                ('students', models.IntegerField()),
            ],
        ),
    ]
