-- ASSIGNMENT-3

-- WAQTD DETAILS OF EMPLOYEES WORKING AS CLERK AND EARNING LESS THAN 1500.
SELECT * FROM emp where JOB="CLERK" and SAL<1500;
-- WAQTD NAME AND HIREDATE OF THE EMPLOYEE WORKING AS MANAGER IN DEPARTMENT 30.
SELECT * from emp;
SELECT ENAME , HIREDATE from emp WHERE JOB="MANAGER" and DEPTNO="30";
-- WAQTD DETAILS OF EMPLOYEES ALONG WITH ANNUAL SALARY IF THEY ARE WORKING IN DEPARTMENT 30 AS SALESMAN AND THEIR ANNUAL SALARY MORE THAN 1400.
SELECT * , SAL*12 as ANNUAL_SAL from emp where DEPTNO="30" and JOB="SALESMAN" and SAL*12>12000;
-- WAQTD ALL THE DETAILS OF EMPLOYEE WORKING IN DEPARTMENT 30 OR AS ANALYST.
SELECT * from emp where `DEPTNO`="30" or `JOB`="ANALYST";
-- WAQTD NAMES OF EMPLOYEE WHO IS EARNING SALARY GREATER THAN 1100 AND THEIR DESIGNATION IS CLERK.
SELECT ENAME FROM emp where SAL>1100 and `JOB`="CLERK"
-- WAQTD NAME AND SALARY, ANNUAL SALARY AND DEPTNO IF DEPARTMENT 20 SALARY GREATER THAN 1100 AND ANNUAL SALARY GREATER THAN 12000.

SELECT ENAME , SAL , (SAL*12)+`COMM` as ANN_SAL , `DEPTNO` from emp where `DEPTNO`="20" and SAL>1100 and SAL*12>12000; 
-- WAQTD EMPLOYEE NUMBER AND NAMES OF THE EMPLOYEES WORKING AS MANAGER IN DEPARTMENT 30.
SELECT EMPNO, ENAME from emp where `JOB`="MANAGER" and `DEPTNO`="30"
-- WAQTD DETAILS OF EMPLOYEE WORKING IN DEPARTMENT 20 (OR) 30.

SELECT * from emp where `DEPTNO`= 20 or `DEPTNO`=30;
-- WAQTD DETAILS OF EMPLOYEES WORKING AS ANALYST IN DEPARTMENT 30.


SELECT * from emp where JOB="ANALYST" and `DEPTNO`=30;
-- WAQTD DETAILS OF EMPLOYEE WORKING AS PRESIDENT WITH SALARY OF 4000.



-- WAQTD NAMES, DEPARTMENT NUMBER AND JOB OF EMPLOYEE WORKING AS CLERK IN DEPARTMENT 10 (OR) 20.
-- WAQTD DETAILS OF EMPLOYEE WORKING AS CLERK (OR) MANAGER IN DEPTNO 10.
-- WAQTD NAMES OF EMPLOYEES WORKING IN DEPARTMENT NUMBER 10,20,30,40.
-- WAQTD DETAILS OF EMPLOYEE WITH EMPLOYEE NUMBER 7902,7839.
-- WAQTD DETAILS OF EMPLOYEE WORKING AS MANAGER, SALESMAN, CLERK.
-- WAQTD NAMES OF EMPLOYEES HIRED AFTER 1981 AND BEFORE 1982.
-- WAQTD DETAILS OF EMPLOYEES EARNING MORE THAN 1250 BUT LESS THAN 3000.
-- WAQTD NAMES OF EMPLOYEES HIRED AFTER 1981 INTO DEPARTMENT NUMBER 10 OR 30.
-- WAQTD NAMES OF EMPLOYEE ALONG WITH ANNUAL SALARY FOR THE EMPLOYEE WORKING AS MANAGER, CLERK INTO DEPARTMENT NUMBER 10, 30.
-- WAQTD ALL THE DETAILS ALONG WITH ANNUAL SALARY IF SALARY BETWEEN 1000 AND 4000 AND ANNUAL SALARY GREATER THAN 15000.
