CREATE TABLE DEPT (
    DEPTNO int PRIMARY KEY,
    DNAME  VARCHAR(14),
    LOC    VARCHAR(13)
);


INSERT INTO DEPT VALUES(10,'ACCOUNTING','NEW YORK');
INSERT INTO DEPT VALUES (20,'RESEARCH','DALLAS');
INSERT INTO DEPT VALUES (30,'SALES','CHICAGO');
INSERT INTO DEPT VALUES (40,'OPERATIONS','BOSTON');


SELECT * FROM dept;


CREATE TABLE EMP (
    EMPNO    int PRIMARY KEY,
    ENAME    VARCHAR(10),
    JOB      VARCHAR(9),
    MGR      int,
    HIREDATE DATE,
    SAL      decimal(7,2),
    COMM     decimal(7,2),
    DEPTNO   int,
    FOREIGN KEY (DEPTNO) REFERENCES DEPT(DEPTNO)
);

INSERT INTO EMP VALUES(7369,'SMITH','CLERK',7902,'80-12-17',800,NULL,20);
INSERT INTO EMP VALUES(7499,'ALLEN','SALESMAN',7698,'81-02-20',1600,300,30);
INSERT INTO EMP VALUES(7521,'WARD','SALESMAN',7698,'81-02-22',1250,500,30);
INSERT INTO EMP VALUES(7566,'JONES','MANAGER',7839,'81-04-02',2975,NULL,20);
INSERT INTO EMP VALUES(7654,'MARTIN','SALESMAN',7698,'81-09-28',1250,1400,30);
INSERT INTO EMP VALUES(7698,'BLAKE','MANAGER',7839,'81-05-01',2850,NULL,30);
INSERT INTO EMP VALUES(7782,'CLARK','MANAGER',7839,'81-06-09',2450,NULL,10);
INSERT INTO EMP VALUES(7788,'SCOTT','ANALYST',7566,'87-04-19',3000,NULL,20);
INSERT INTO EMP VALUES(7839,'KING','PRESIDENT',NULL,'81-11-17',5000,NULL,10);
INSERT INTO EMP VALUES(7844,'TURNER','SALESMAN',7698,'81-09-08',1500,0,30);
INSERT INTO EMP VALUES(7876,'ADAMS','CLERK',7788,'87-05-23',1100,NULL,20);
INSERT INTO EMP VALUES(7900,'JAMES','CLERK',7698,'81-12-03',950,NULL,30);
INSERT INTO EMP VALUES(7902,'FORD','ANALYST',7566,'81-12-03',3000,NULL,20);
INSERT INTO EMP VALUES(7934,'MILLER','CLERK',7782,'82-01-23',1300,NULL,10);




-- WAQTD ALL THE DETAILS FROM THE EMPLOYEE TABLE.

SELECT * from emp;

-- WAQTD NAMES OF ALL THE EMPLOYEES
SELECT ENAME as Employee_Name FROM emp;

-- WAQTD NAME AND SALARY GIVEN TO ALL THE EMPLOYEES.
SELECT ENAME , SAL FROM emp;

-- WAQTD NAMES AND COMMISSION GIVEN TO ALL THE EMPLOYEES.
SELECT ENAME,COMM from emp ;
SELECT ENAME,COMM from emp where `COMM`!="NULL";


--WAQTD EMPNO AND DEPT NUMBER OF ALL THE EMPLOYEES IN EMPLOYEE TABLE.
SELECT EMPNO , DEPTNO FROM emp;

-- WAQTD ENAME AND HIREDATE OF ALL THE EMPLOYEES.
SELECT ENAME , HIREDATE from emp;

-- WAQTD NAME AND DESIGNATION OF ALL THE EMPLOYEES.
SELECT ENAME , JOB from emp;

--WAQTD NAME, JOB AND SALARY GIVEN TO ALL THE EMPLOYEES.
SELECT ENAME, JOB , SAL from emp;

-- WAQTD DNAMES PRESENT IN DEPARTMENT TABLE.

SELECT DNAME FROM dept;

-- WAQTD DNAME AND LOCATION PRESENT IN DEPARTMENT TABLE.
SELECT DNAME,LOC from dept;


-- WAQTD NAME OF THE EMPLOYEE ALONG WITH THEIR ANNUAL SALARY.
SELECT  ENAME ,SAL*12 from emp; 



-- WAQTD NAME, JOB FOR ALL THE EMPLOYEE WITH THEIR HALF-TERM SALARY.
SELECT ENAME, JOB from emp where SAL<10000;

-- WAQTD ALL THE DETAILS OF THE EMPLOYEE ALONG WIT AN ANNUAL BONUS OF 2000.
SELECT * from emp;
SELECT * from emp where BONUS=2000;
-- WAQTD NAME, SALARY AND SALLARY WITH A HIKE OF 10 PERCENT.
SELECT ENAME,SAL , SAL+(SAL/100)*10 as NEW_SAL from emp;
-- WAQTD NAME AND SALARY WITH DEDUCTION OF 25 PERCENT.
SELECT ENAME ,(SAL/100)*25 as DEDUCTED_SAL from emp;
-- WAQTD NAME AND SALARY WITH MONTHLY HIKE OF 50.
SELECT ENAME,SAL , SAL+(SAL/100)*50 as NEW_SAL from emp;
-- WAQTD NAME AND ANNUAL SALARY WITH DEDUCTION OF 10 PERCENT.
SELECT ENAME ,(SAL/100)*10 as DEDUCTED_SAL from emp;


-- WAQTD TOTAL SALARY GIVEN TO EACH EMPLOYEES SALARY PLUS COMMISSION.
SELECT * FROM emp;
SELECT ENAME, IF(COMM IS NOT NULL, SAL+COMM,SAL)  as Total_SAL from emp;
-- WAQTD DETAILS OF ALL THE EMPLOYEES ALONG WITH ANNUAL SALARY.
SELECT * from emp;
-- WAQTD NAME AND DESIGNATION ALONG WITH 100 PENALITY IN SALARY.
SELECT ENAME , JOB , SAL as PENALITY from emp;
